sudo: false
os:
- linux
language: haskell
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
- stack sdist
- cabal --version
deploy:
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
- provider: hackage
  username: "$HACKAGE_USER"
  password: "$HACKAGE_PASSWORD"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: Td6mXi4ejcTdCeQBSvBSRWhka6AfEnWWoihG20ZV0IJE+3vsts3ZneerWOO0U3bcmoN9joLu6uyEBjDBMfZM9WYoresVJ4/xAPmz8+52XUHgs9UpX/vde8chMtc7Ty56KM6+S7CaWCmOYLgsuHRDSMJk7INaDGfi87n9PbPqq8is/HryQOinMfORaVWhuEhB4dNbI2TAvOKet7PsZ8kID7QcxGvY0pH/6GH/oC365wYFwK9cskOkZr0dE6O6+4Kw7nWQeuewlDHpVcF4PtEiTkjl1MH8+TWu1qbanS8yKBjXjHXDbX5MDz8eO/+8cEayQOkDrq8BZll+ralF2+nVaiRj8y8tdrQDP2IsG0au6Q6VDX2H70vgXb8FC6cY8yNoDRN52Zm9lLwEAfY3A5Jvg4tpYzfhU/w7XkXWltxpkjil3uNB7b1tlxYfnc17c6YK/tgQRStJ/3kFK9mby7HZo4GDt6Cv9GDb7/MdQ6Rp9dwR7kvRw98kqIwyR6rW3C46be1GlwY4FVc2qPY0WVxzV7i0pCaJjomZA2ID8n5rgW9ji73z+HHVJb9xjdyGwbcnc5qTPTTQhgK5BzkDj8lWF0mjodM7Xlz0xP+Nv9dM262MzQb4dI9rEGmiC+tzUQLZD9Z5apD/ChNdf0OQerAql618HpTOpiBPA/wiJ4vmjfw=
  - secure: F6U4Q0QMl1lAhFcGHZL2oww+f7HSAoCNxHATyn0PYwDvqCut6WEAotRnTb+XGZF8anEhp/h/PsdVmHxkJ7B92FEkkEa0/5DAH6uu6uKPgZDAPTRMc+LajcYPSM0z/re3Onp9DwypsVMPfu+1dz515GsS2I4JnZ4dBJ/rLmugsIIBKYBlodPQkBqvmu0zqFTGuAfZ8u9CsaGS1BZIgduwjTPZhoUecjC4/kIPBz8ocShI1jhgmDrzvuKQXSggiFxIEwWnCG33vPVEIRjfANjgFV//4amJqHYf8X//1TVrO+YJqgPEDYayAQISS9Ox6D3/hRDjezmw5gp9ntATZ9tcESZKE2owshzkCTitPHfXt6C7B0ehWbNuGMyR9fyIoqT/iK2INn7ORzZ4Gtc+wVvtagaqpZfzAcKpo7fmv6oqR1g9p8f8YovHAJIozSGh282koMF2MGX2nkKnT8B+cVzyAsTpQPxUSJW0X66V8CqYbFWnecUgvWSCQ0kxapU8p+VhtWbwKL6vmNPf0Hmh57s1S1a30v7qyAoo4OlTPeNXzrAiS6Q4Lh4mKmT6XWuGvffbJ9elLVArr8B3XZRkcsZeGhsl/GcMu02Zy/F7FC7nRuMLwzSrG70mXFMe2hIrYM0tjiqTfs/9Rrpnt1TXjFZ8yI8pk4oGn3MTH9Ba3SQ98wA=
  - secure: bf7DnluB0TQdaazYiZPOdBYMhVrfaGeCnBblfedMGb3rT+3IWFMorn100dkEgNLUe0NzREwwEYQjygDkIb2MWq2D8V2bRREXL/SNeFwE49teWl5pJ4Ef4vmDNnEjW02P7zoowR0bXZA2G8GfpynjJSBHrLCabv7sK5G9mau37QZwQ0G4RX4qXBdLFOdRWuQRPiTLJGi2YEql1BY7TubobMRXku73MDCfaPS4b0/QlwJBGc10Q6rtidu1M3hGYM0yiFs0AWa9HzYuDqJzLAMbyituE9k1e8k2m1UA+TmAZlshRg9JUffLTCyTRefxw+7xvkHzkLRSBrRHs5D1XFdiee9Du6JTD+s7YBFfS0zLBG8hqze97QVXorKGl2vUB6zkSzmJ8bU2lI+sUiv4ZfnWMyYM39IBdr407jonWXGx5fhZNG8k0sYtLg81NvD/b6opNRAYZwcFprZndyIrn54nNI6xeXk6L9fDzeIun6a5C4oSdX+wpLQ5Up1U/GLq1mziH3rCSR9kw1OfJ72F5DS51vjIqZTvBqOt/bdRfPyFJ/+RS8rvh++ZEZT5OKvrblxO8WlFB+VmwXGWWnkW6AkGT7UEmaKr0wZWSXAUW6KGBlmp16J4WC8DMWe9YpGeJJSsanUYrnXV7oNpp0gjzVH0n/mxMKnLFaxEWsLGqOSPzeY=
