sudo: false
os:
- linux
language: haskell
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: script
  script: bash deploy.sh "$HACKAGE_USER" "$HACKAGE_PASSWORD"
  on:
    branch: master
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    tag: true
env:
  global:
  - secure: Yq9va/3jGZN5YplSvA/1f7IvFXaXiWbbeWaOWz3dUsM856Kxn2OhDLYvM6zUrHrK4zSCFwDVE37205h/F4BsNqzC6SqFgvd5SN4whYCTYh52OnfWm0cVcfgP59m+3E6VVBxi77/fmbYHn+TfUCL9lj/XeOGr4QjxQK5FpWSZRq/9mvARPxtALIRF5gx6rPNGP0iXNh1DpGojd7AX9pxoRXc9nbZRqwIWi2giLx3w8XH2aPpxsRRO5hZDGxx+DZdbp15i6h1WK5qDdNq1T28l1NzHpS3TSZ23tUdCvNDwEHRPVM7NgMp+Jmd36i+gNNw8V711LQI66IfcA7KZpiKcXKmteUE3jtNgw0gX1c8mSAP3Sag+Cfx335suGwW+mTlxystEdv1JnHA/Sefeatf1E6GegNHZqNQN0XgvkHoLCB+tOEIrtBGvFi2V5mzO5UjGdAZnXkYHLhHCJC/D6V57btUQoCBtLw4nMQrDALKXWQjPlglM4vJQwoHNbWQtg5LkHDz9QGNg4j6dOssGPbw9MV8O0yD+a25GzPe4B7+0yo/nb/z+aLUZAbVP5G8YR+73GOpYtlQ85x5CYIqWgXN0z4Y2oB+rcVsT8aZazqfveRDd+FEmo7vi9jW6ebsXRTBDq4DE87T6hDqJRSUSxbeVPj6sN+GfYEwbfjQXZOusoWs=
  - secure: jIyP/P5QfbvjkWAxPbLUfythJINp7PSWsplKTnn2adydW+za8bEarg3eH9cf0T67y0UORMIyFvqOtRD8UhEWRc9v91H99srb03OVzF7O91yBxtEngrJPMbn9OZLYl2PLgWM6BEFlwYadjfNWSFy12ZD34QC7jCivl3h/MbeE+25kXVI0Se8+KswWHhlXBMCc8mGYE1fHhx0cka2bRSeo856TjRTi3IbLnB2UNiCl3Q2IfVBcXhNLr7xC9TFurMgEhkpAyL++rDYk8tqlXwZ1TME3IfwPD6CXaUdNw9koeftWP2XUWZQNNrx998B+dvMgXHiEqp3ZzFXybP2xg1w9N+CuUE4KyqeFKyLSJA5GsedWlQvHu6B4ZZV1nb8F/P2+aFmwVgS5v2XSFN2aMHpBWtalYQ8msCNdWORalDUzVZYncLx1w9oBAODZvxRTseXDJMy2ZOI4CvkIcMaqJcJ7QZNd1SD60gk84N5+MZky7IQeA2BnP6z0DTzPK2uQRZEilfK9rDrCP2wPtjfU5ijvLqXnqoE3idgQCT5UYy3nMprXccHUyn52/bayNCPpHx2NjRyDlCiPXlPUsbsegU+OQtDrc0ddVoP6A1ACvpJJxvIoZS/4xmi5F5J7Ieh6HQhV+KRXcBI4PGQ7unrz2INQkszkAp172yEeRBzcJIH46Hk=
  - secure: fbcMVy/1d9PmkBcorphb92FzFz04d6kaGj1wmA2t5/kbjeSZnNKRlQNP5gJO20MNW3NIhVR6LSxvGjYb/zy62R+YY9AbMrcVSunjTYsZ3sT72p7x+qHZ12sfS3qqrI5zmIFSD5hQeht0NUzozXY9aOI88OhBUfuatgyOf3do3d0+hgvekD82F6G19xenK4uM1OnQWikdVnhXhynFj/RymJzH6Cg8RLym1eMRiWgPSp+LQteAaFw63NaVxUTUD5dXZmCas002f+vhoeEDAwdLMdxMSQ3Lo+Ah9M2XIuo9Ej+3JTGms/aHQEYjMJBPC25aQZRUAbqFDtNNA0pSZm50bNMX+YtPQ4vIn1vAyHUtZ3uFMomAgR2AE/OQZnBAA1O5qLNH+Ih759CA/4Y34U1telHnXlT0hJ47nZ86dk4vNCToIrthWD0TLKN8m9Ew9yXCvB7Gxtbaa/P2b1RTSrZQqFrHMhEg+ygFBSXtXRNwMp+WdnlEBRSWUyLmNbgpC3rkJp1YEMhSGB0Zv+ilHEyNNVLEj9bRvh5FY0usVRVk0fhg2Fvj4iyXB2fale9+RgwJLKUC9Il/C/74UIYX1fjkfzRDlQHtCjQp6+Ai0Ujh8wAJ1eWDYeP6XeDB9nnOuUSjCsOS13KdddaidwkGa28SQ6dQQgBfh76Z8+jTAE3CAsA=
