sudo: false
os:
  - linux
language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack build

script:
  - stack --no-terminal --skip-ghc-check test
  # verify that there are no hlint suggestions
  - curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
  # verify that there is no missing documentation
  - stack haddock 2>&1 | ! grep -q -i 'Missing documentation'
