sudo: false
os:
- linux
language: haskell
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: script
  script: bash deploy.sh "$HACKAGE_USER" "$HACKAGE_PASSWORD"
  on:
    branch: master
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    tags: true
env:
  global:
  - secure: PN9GsOvfd1FGVN1uYVIRnjKkHADyXWwWkkZepOzZ2wY5/aCK23DxcxpXuCL1FgTrjKLK5ockFwDlhGOobLwU5H0uQx8IhQ2p0fPYNbpUb9CFK4acF2AOclXR4fGM9opqwzApYHc+56Fx9aEQqM2BKV5Y9p1mAAm4kutOYDoTixMVvCYe/LSj12H/r4DqZ67JLbNs8P/i/7C09+ibE5dZu3VYDd8oDMHGltp6l0tNvBBb2VpCkMyfCHUYX/JnyHC76f9QmTvNT+1TmMd9d14h5ZMYHgqBNBFxHGjYkNG9CNVSMwiHfL54atr+3jPKbgWcGBSLgnMGkQzCVCxXmY1b02vU5mzVaAR3N+mn7uNWpZQOWeQY14kh0J/Vm1ztyCnOAfrHQwJBbtio0wMknpsQIzwh78qdqv4cEkTPKywT2xIUNJBbaAauiqX+Eg5Vs8VexG/e6JBm6P62oDJg073XQ6ma0QphfHc/ozFuoUq3nY8RHmXJvg59c8jFZaO5DHf3kJgBcaCRbMZnMZuhS0z5RpU/8G8jsWp4/TXymMhDbPeB3vstJtJU4faTfnTwWyTnCd9cBkBM9Se8qSjU3WllBktg522x7gKsMnb80GdOx/b0BRSkCwJ5UdyKhRf5o/fnXbKZUWjjgX5wX0B5FASSAPLlu7YlrD3qjPbAxpF7v7E=
  - secure: b9po6LjF6l9bvdmZFYc6b7+VW495sish3jv4Y1Z2j74J0Cl5B4hkLUqbTSM8/fPwInrBKSvG8WfNV0rv2a9QDPPPA6d/JTHarYSFLF3EMfy/RvV8sWn0kCXtiMbeLAjdoYlEnd4qLVRYrKSg3k4ImTz0rF/E2Ll/8A6snHPFFnR+9BFBgYUPswTdi/XmJd7FXETGIHDplf4RDBjXI/Yc3aiVa1d+8t0vPtfGTuPUbjYOYth+hnyh8NFAGIgSAv9xpdF8WAjnZF8MSLAMWvRGwJtlaWueOojC/jtqYT63gAHoSk9KboqMOcvzMeiowl0B+OU1/jbX03a/5RlkZch0nNR7RObYPW72fC1/HYBsDLV3FxYtJDItWkcMldDPJIwj2LPtkUiOcw2JJFPfS2OFgfcTnwVIHuyzkouHtS+iJjbkXYpVp/nlc2gizc0ZpsV5eSfG9J9XvQ8Eglju/h1LScc6qU72m8HdNALM4edg/7GLb9tuzgcllpzjos97lcB4+jhi2iPJWIHOiscRV9CzFhB2gEzKj1ypg/cTZ7umfIg4ZwnysFKTABcDozhT3x0Vsgj+ZaFGVki4tuMiUsGAsEdMVrbqBQ5BkL1hwYnF+87375ghEP21wkKxIe0m2PyG03rUHmR+B96R1hwzmL1k/iEbrjaJl01Y2xJ3BmZSqhQ=
  - secure: I8Q+LmAiLkolrUqibZpXPOPLWPmzgnb8SJ7E8Lm9h1i5nj59/eTCzs/DOGXkbwYqSpht7l3A0M/cCbHIV7VGujMbSt+Dd/U1LFdNR1FHfEmNApVdT2ephieCbmsbgEglgHx74jxa5vUaQHckExK+0Xnfx8UXyQq4JzLbJybonYX0LfGv0fHjW7uZXSF/LxMURTP9MVHeU8WKkTVEpIKxR/1YDKTavCC8fEGxWyGceKOmz4Gz+0bzkxgZTn9KPfvXnl/iSU4hHOjGe/sUn0csVJzyIaxqq7NXnurhPvKG6m0jFncZyaiknsdDwEOdkHmB2Svcs3JzY8OPy3PESGlH/nEBZa+4PyjhrtfWeMLxI1jchecQiZhEJ9QX19lob6TbnFq5hCgcidy9SuVKB+CenH0iwWXO3Wf52OujiwbwhPzQ36Fg3Cliq2jneIUwWeW8SM4TGQIJy7E/fejxs7tErCwdsrjPHSLv/Hb4MbYMPyPM2rHome8fetncxmXM29f7Sv2FF1SNzpcaIfqTbFbGqM1MpYvTtalDs2RzjiFpqLyuScRNwoaOVwKpryQ0xZ+VKYlM8myswZ78aJXHIMl2lNRk++048GpBYYj9qxhsi8ngSdTR019z+2b64VGfe/UvAwIyVZUgiPyxMgshmmA+ICiMl52VuSjQQceGX2ljoEQ=
