sudo: false
os:
- linux
language: haskell
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: script
  script: bash deploy.sh "$HACKAGE_USER" "$HACKAGE_PASSWORD"
  on:
    branch: master
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    tags: true
env:
  global:
  - secure: l9c4xWY8AmSgJ98UJ5fQXv5Gf6xoE6P5SPAfRSSnrBr7F8s9z7cZjQjkXNyI0s74q5ymyRcmY/H0sJyrcGq3WF9ygrguyvedcsF1h+I10UPYDOiI7xUraDJvGJ5UlrCOsAXtzPIxETh9z64N9D1pm4uBsvyxr7bIfRljZ/iMt+yTGeDJMl2IXR2o7AdeHqKEl88baJTfFXRX82Sm7coJKVjICtuMSH1qcgy1LTIxvgflzhV4C2nbmmiSu8buZ3AuKX17l+0tcTellHL8WxLyVYA3/HQHbqS7qW1Lf3hsIeAlWlr6lcW/DCs67clD/1jD7+j2Xr3XwTuWhI75d6SZDLkAJKeKz+kpJlziGnaNjlboE/dWEtK4DPL6/WIXxxxRMwglbpBxphCvb3xHISOn2TZ6N4Nvi6hchmZMbOLIa20xgpvu8MSG1ClbDh6pPRgqeCwqpSTjVbBbqskeVmX8Wq/WClGbx99XsYZLSeY3R/BdrepqYLfaBjuaNm3tNRscnNhblBwlRxf4tIqHZRS4V7FGFoKVgzo9orcAit1SB9KHXiWjdUW4Lt2FxkxwCVgGW+CO+F7TIm0AEbB6mcRE1xOJ0qh5kvMej/NtQpBnn7aaVIFvLjOhh8QSQW+cvPdZkXRe3dIyg5UX7q1s1vox44r8xvM/D9IDJu+bq3N5DRI=
  - secure: qLQZML7fGeV6Zel0otFPhORERHEjHSms4O90SH9WpnLYAS5bet27x9Nju4wsOIpbKU3+hOBnjWV+zaXchWiokU+pTpCjTNu2S1G7xRTQjQMOZAEa8smRuegSUX+pG3hEWTOszdiNF1mBwOpr+SbrWbp0nLJ4bv+klZjzBrrUqdGbnrsUuzJKOkZjxwsobmK+IrjTy9Nf7hsEIX4hIEqBAxhOtfvEBrc7PxG2AsBxqGZVfFIWS3R+DY2gdg1ZJAX0vXKsUJ69DrITK96odGlhfzi/7DHfqd1YjqBxXbpGcKbIzecx5EyFgCjTzPcQJsZZde49lu5517ekL5I9PJqAMeh5329tdMlrM8VlgBhfKkZskAvNsq+4Vxy3Ci1w6WZg3yY3cmF6wZvy4YqbPEI/R11AeZBtXPnay/Xfp/c2R7xm+uNBw4mcrcD3BVWpdkMoUb0w5LB1QG011eUlpc7ZtKtAtYkKhSn1rYM7v/hlQl5LkYIqFFkt/M0GHCtHWYCnzRzgxd7RuUZJH7jdYzHDUACzVkEpDWfoc/oumAj6vLo3D2vDM61dTC8kbazboPYWlT4ymeuAQDXUuMfGXTN1IQ9P1jcO1mdT5S6HmRF2Mx29PPvdADvDdc7H8OXY3kcha4Fu5khO8HtalLULOa/OKAMwuIOa90wf2/6HL0CaIhA=
  - secure: HFaRT9rQtcuqv6noaomfnIaygpuYMBy5z6FykefEyBfSJYsSPJNrlNJ9hcZFHQwOiAuSB3MK8Ts0/sEzNPxsPyHaFC+ekTVN7OilIN95oFQ4YR14cK7drwmrrjEbNYseNH9mYQvF8atqpMb3Ug+Zu/TaqOVGf43tm93o6n++HvSZ1n/CaATTiCYpOfGnVxixqMFZ1QK1oeetkzrKqNtbh8j6XbyMw02wiPrHDTM78tSGnkJdlixLPqttMPjrphH/VTHJm5b7vkxzgI65QGZpwSTl6NvWvff4dgobvyurJvCx3HA9kn9rpPx5SIwmye2S6I4/w1y4000gk0uNqll11mXqHBv/yLtJZtjwIAbkCiaUggSY10zd++xYfk+Sd0CXbw6Tm4kWFyuZ776f113EpeHd4rRfn17S8fg6A2Str+4OLd1FS5KCkzRox/QBnH3AFiD8guVo0gjbch6qhDTP/GAiUQohim5Gp/yimQOPs0eqxvDy+gfz61IauPN7PSEsDOSBTBqbQ2tBvCk+FJs/duFWlsD+diKNWResj7sOF4tVG5niI4RDw3jTEoCrkMbPOL1qkrtj5vi2XmuQYivznLL7QaeWrCKY47+jq1LydwDQ01Q2URA9tB6DjgthjhVhfA4wU4WFwy0bWB5EUO/sQ7EtGrXPmHATGKJk2lnxYUw=
