name: CI/CD
on: push

jobs:
  linux1:
    name: Build the Haskell software
    runs-on: ubuntu-latest
    steps:
    - name: set up Haskell environment
      uses: hapytex/github-actions/setup-haskell@master
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: build haskell project
      uses: hapytex/github-actions/build-haskell-project@master

  linux2:
    name: Build the Haddock documentation
    runs-on: ubuntu-latest
    steps:
    - name: set up Haskell environment
      uses: hapytex/github-actions/setup-haskell@master
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: make Haddock documentation
      uses: hapytex/github-actions/run-haddock@master
      id: haddock
    - name: echo path
      run: "echo '${{ steps.haddock.outputs.haddock-path }}'"

  linux3:
    name: Look for todos
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: look for todos
      uses: hapytex/github-actions/look-for-todos@master
      with:
        directory: src


  linux4:
    name: Check for hlint suggestions
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: look for todos
      uses: hapytex/github-actions/hlint@master

  linux5:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
    - name: set up Haskell environment
      uses: hapytex/github-actions/setup-haskell@master
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: run the tests of the package
      run: stack --no-terminal --skip-ghc-check test

  linux6:
    name: Deploy documentation to GitHub pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: hapytex/github-actions/setup-haskell@master
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: make Haddock documentation
      uses: hapytex/github-actions/run-haddock@master
      id: haddock
    - name: deploy the documentation on the GitHub pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: "${{ steps.haddock.outputs.haddock-path }}"

  linux7:
    name: Deploy package on hackage
    runs-on: ubuntu-latest
    needs: [linux1, linux2, linux3, linux4, linux5, linux6]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: hapytex/github-actions/setup-haskell@master
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: make Haddock documentation
      uses: hapytex/github-actions/hackage-publish@master
      with:
        hackage-user: "${{ secrets.HACKAGE_USER  }}"
        hackage-password: "${{ secrets.HACKAGE_PASSWORD }}"
